---
title: "hw03-Tianshu-Zhao"
author: "Tianshu Zhao"
date: "2017/10/15"
output: github_document
---
previous setting (ignore) 
```{r}
library(scales)
library(ggplot2)
library(readr)
library(dplyr)
# Import tables
setwd("C:/Users/ariel/stat133/stat133-hws-fall17/hw03")
data_stats <- read.csv("./data/nba2017-stats.csv",
                       stringsAsFactors = FALSE)
data_roster <- read.csv("./data/nba2017-roster.csv",
                        stringsAsFactors = FALSE)
# Add variables
data_stats <- mutate(data_stats,missed_fg = field_goals_atts - field_goals_made)
data_stats <- mutate(data_stats,missed_ft = points1_atts - points1_made)
data_stats <- mutate(data_stats,points = 1*points1_made + 2*points2_made +3*points3_made)
data_stats <- mutate(data_stats,rebounds = def_rebounds + off_rebounds)
data_stats <- mutate(data_stats,efficiency = (points + rebounds + assists + steals + blocks
                                              - missed_fg - missed_ft - turnovers)/games_played)
summary(data_stats$efficiency)
sink()

# Merging Tables
teams_merge <- merge(data_roster,data_stats)

## Creating nba2017-teams.csv
#create a data frame teams
teams <- summarise(group_by(teams_merge,team),experience = sum(experience),salary = sum(salary),
                   points3 = sum(points3_made),points2 = sum(points2_made),
                   free_throws = sum(points1_made),points = sum(points),
                   off_rebounds = sum(off_rebounds),def_rebounds = sum(def_rebounds),
                   assists = sum(assists), steals = sum(steals), blocks = sum(blocks),
                   turnovers = sum(turnovers), fouls = sum(fouls), efficiency = sum(efficiency)
                   )
summary(teams)

sink(file = './data/teams-summary.txt')
summary(teams)
sink()

write.csv(team, file = './data/nba2017-teams.csv')

# Some graphics
pdf(file = './images/teams_star_plot.pdf')
stars(teams[,-1],labels = as.character(teams$team))
dev.off

library(ggplot2)
ggplot(teams,aes(x = experience, y = salary,label = team)) + geom_point() +
    geom_text(aes(label = team))
ggsave('./images/experience_salary.pdf',width = 5,height = 5)
```


##Ranking of Teams

#Basic Rankings
```{r}
library(ggplot2)
library(dplyr)
library(readr)
library(scales)
setwd("/Users/ariel/stat133/stat133-hws-fall17/hw03")
teams <- read_csv('./data/nba2017-teams.csv')
teams %>% ggplot() + geom_bar(aes(x=reorder(team, salary), y=salary/1e6), stat="Identity") +
   geom_hline(yintercept = mean(teams$salary) / 1e6, color = "red", size = 2)+ 
  coord_flip() +
  xlab("Team") + ylab("Salary (in millions)") + 
  ggtitle("NBA Teams ranked by Total Salary")

```

```{r}
teams %>% ggplot() + geom_bar(aes(x=reorder(team, points), y=points), stat="Identity") +
   geom_hline(yintercept = mean(teams$points), color = "red",size = 2) + coord_flip() +
  xlab("Team") + ylab("Points") +
  ggtitle("NBA Teams ranked by Total Points")
```
```{r}
teams %>% ggplot() + geom_bar(aes(x=reorder(team, efficiency), y=efficiency), stat="Identity") +
   geom_hline(yintercept = mean(teams$efficiency), color = "purple", size = 2) + coord_flip() +
  xlab("Team") + ylab("Efficiency") + ggtitle("NBA Teams ranked by Total Efficiency")
```

## Principal Components Analysis (PCA)

```{r}
# select the variables that we are interested in from teams
team_new <- teams[, -c(1, 2, 3, 7, 15)]
# create pca object (containnig all the PC's)
pca <- prcomp(team_new, scale. = TRUE)
# add PC1 PC2 back to teams
teams_with_pc <- mutate(teams, pc1 = pca$x[ ,1], pc2 = pca$x[ ,2])
# rearrrange team by PC1 in descending order
select(arrange(teams_with_pc, desc(pc1)), team)
```

Createa a data frame with the eigenvalues:

```{r}
eigs <- data.frame(
  eigenvalue = round(pca$sdev^2, 4),
  prop = round(pca$sdev^2 / sum(pca$sdev^2), 4),
  cumprop = round(cumsum(pca$sdev^2 / sum(pca$sdev^2)), 4)
  )
eigs
```

```{r}
teams_factors <- select(teams, points3, points2, free_throws, off_rebounds,
                        def_rebounds, assists, steals, blocks, turnovers, fouls)
pca <- prcomp(teams_factors, scale. = TRUE)
teams_pc <- mutate(teams, pc1 = pca$x[ ,1], pc2 = pca$x[ ,2])
teams_pc %>% ggplot(aes(x=pc1, y=pc2, label = team)) + 
  geom_text(aes(label = team)) + 
  xlab("PC1") + ylab("PC2") + ggtitle("NBA Teams ranked by Total Points") +
  geom_hline(yintercept=0) + geom_vline(xintercept=0)
```

```{r}
teams_pc <- mutate(teams_pc, pc1_rescaled = 100 * (pc1 - min(pc1)) / (max(pc1) - min(pc1)))
teams_pc %>% ggplot() + geom_bar(aes(x=reorder(team, pc1_rescaled), y=pc1_rescaled), stat="Identity") + coord_flip() +
  xlab("Team") + ylab("First PC (scaled from 0 to 100)") + 
  ggtitle("NBA Teams ranked by scaled PC1")
```

Use the scaled PC1 to rank the teams:

```{r}
select(arrange(teams_pc, desc(pc1_rescaled)), team)
```












